//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaLance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engg
    {
        public int ID { get; set; }
        public Nullable<int> Posts { get; set; }
        public string Projects { get; set; }
    }
}
