//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaLance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects1
    {
        public int ID { get; set; }
        public string ITTech { get; set; }
        public string DesignMedia { get; set; }
        public string DataEntry { get; set; }
        public string Engg { get; set; }
    }
}
